version: '3'
services:
  credia-nginx:
    image: nginx:alpine
    container_name: credia-nginx
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    tty: true
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./:/var/www
        - ./nginx/conf.d/prod/:/etc/nginx/conf.d/
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
    networks:
       - credia-network
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  credia-app:
    container_name: credia-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: credia-app
      SERVICE_TAGS: dev
    build: 
      context: .
      dockerfile: app.dockerfile
    working_dir: /var/www
    networks:
       - credia-network
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

  credia-db:
    image: mysql:8.0.20
    container_name: credia-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: wMnck4aG3DJv6JoUYN3y
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - credia-network

volumes:
  dbdata:
  
networks:
  credia-network:
    driver: bridge
