version: '3'
services:
  credia-nginx:
    image: nginx:alpine
    container_name: credia-nginx
    restart: unless-stopped
    tty: true
    ports:
        - "80:80"
    volumes:
        - ./:/var/www
        - ./nginx/conf.d/dev/:/etc/nginx/conf.d/
    networks:
       - credia-network
  credia-app:
    container_name: credia-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: credia-app
      SERVICE_TAGS: dev
    build: 
      context: .
      dockerfile: app.dockerfile
    working_dir: /var/www
    networks:
       - credia-network
    volumes:
      - ./:/var/www

  credia-db:
    image: mysql:8.0.20
    container_name: credia-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: wMnck4aG3DJv6JoUYN3y
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - credia-network

volumes:
  dbdata:
  
networks:
  credia-network:
    driver: bridge
